### ===================================================
# Lesson 2: Introduction to NumPy
### ===================================================

NumPy (or Numpy) is the main library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. One may think of NumPy as a Linear Algebra library for Python. 

Numpy is super important when doing Data Science and Machine Learning with Python as almost all of the libraries in the PyData Ecosystem rely on Numpy as one of their most important building blocks!

NumPy Python gives functionality comparable to MATLAB and they both allow the user to write fast programs as long as most operations work on arrays or matrices instead of scalars. In comparison, MATLAB boasts a large number of additional toolboxes, notably Simulink, whereas NumPy is intrinsically integrated with Python, a more modern and complete programming language. Moreover, complementary Python packages are available; SciPy is a library that adds more MATLAB-like functionality and Matplotlib is a plotting package that provides MATLAB-like plotting functionality.

Numpy is quite fast as, under the hood, it has direct bindings to C libraries.

To use Numpy you need to first import it into the Notebook. It is customary to import it using ``np`` as an alias:

In [3]:
import numpy as np

<h2>NumPy Arrays</h2>

Numpy arrays are the main way in which we will be using Numpy in this course. We will almost exclusively use only the following two types of arrays:

- *1-D Arrays, also known as vectors*, and 
- *2-D Arrays, also known as matrices.*
    
<b>Remark:</b> there are, however, multidimensional arrays which are used for example when conducting image classification. We will give examples for multidmensional arrays below as well, but we will most likely not encounter them again for the duration of this course. 

Regardless of the dimension of arrays, it is standard to refer to them simply as <b>arrays</b>.

We will cover a few categories of basic array manipulations here:

- <i>Multiple ways of creating numpy arrays</i>
- *Attributes of arrays*: Determining the size, shape, and data types of arrays
- *Indexing of arrays*: Extracting and setting the value of individual array elements
- *Slicing of arrays*: Extracting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

<br>
<h2> Creating NumPy Arrays</h2>
<br>

<ol style="list-style-type:square;"> 
    
<li><h3>Creating N-Dimensional NumPy Arrays From Python Objects</h3></li>
     <ol style='list-style-type:circle;'>
         <br>
      <li><b>1-D Arrays From Python Lists</b></li> First, we create a Python list
        
```python
my_list=[1,2,3] 
```
We can cast that list into a Numpy array:
```python
arr=np.array(my_list)
#Result
array([1, 2, 3])
```
<li><b> 2-D Arrays From Lists of Lists</b></li>
First create a list of lists

```python
my2D_mat=[[1,1,1],[2,2,2],[3,3,3],[4,4,4]]
```

we can cast this list of lists into a numpy array to create a 4x3 matrix:

```python
mat2D_arr=np.array(my_mat)

#Result
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])
```
   <br><li><b> 3-D Arrays From Lists of Lists</b></li>
First we create a *nested* list of lists
```python
my3D_mat=[[[1,1,1],[1,1,1]],[[2,2,2],[2,2,2]],[[3,3,3],[3,3,3]],[[4,4,4],[4,4,4]]]
```
We cast this into a 3-dimensional 4x2x3 array by:
```python
my3D_arr=np.array(my3D_mat)
#Result 
array([[[1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4]]])
```
</ol>
   

<li><h3>Creating N-Dimensional NumPy Arrays From NumPy Built-in Methods</h3></li>

<ol style='list-style-type:circle;'>
<br>
<li> <b>1-D NumPy Arrays From The <i>Arange</i> Method </b></li>
    
```python 
np.arange(Start, Stop, Step_Size)
```
If no step size is specified, the default is 1

If no start point is specified, the default will be 0

Examples:
```python
np.arange(0,10)
#Result
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(10)
#Result
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(5,20,2)
#Result
array([ 5,  7,  9, 11, 13, 15, 17, 19]
```

    
    
<li> <b>N-Dim Array of Zeros</b></li>
    
```python
    np.zeros(shape=(rows,columns), dtype=[float,int])
```
Examples

```python
np.zeros(4)
#Result
array([0., 0., 0., 0.])
#Shape
np.zeros(4).shape=(4,)

np.zeros((1,4))
#Result
array([[0, 0, 0, 0]])
#Shape
np.zeros((1,4)).shape=(1,4)

```


    
    
   </ol>


</ol>

In [40]:
np.zeros((1,4), dtype=int)

array([[0, 0, 0, 0]])

In [20]:
np.arange(0,10,1,size=(2,5))

TypeError: 'size' is an invalid keyword argument for arange()

 <ol>
  <li>Coffee</li>
  <li>Tea
    <ol>
      <li>Black tea</li>
      <li>Green tea</li>
    </ol>
  </li>
  <li>Milk</li>
</ol> 

<table style="width:40%">
<tr>
<th>Name</th>
<th>Address</th>
<th>Salary</th>
</tr>

<tr>
<td>Hanna</td>
<td>Brisbane</td>
<td>4000</td>
</tr>

<tr>
<td><Adam></td>
<td><Sydney></td>
<td><5000></td>
</tr>
</table>