<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [2]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [156]:
#Your code for part A of Exercise 1 goes here


In [ ]:
#Your code for part B of Exercise 1 goes here


In [ ]:
#Your code for part C of Exercise 1 goes here


In [172]:
#Your code for part D of Exercise 1 goes here


<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [173]:
#Your code for Exercise 2 goes here


<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [174]:
#Your code for Exercise 3 goes here


<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [175]:
#Your code for Exercise 4 goes here


<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [176]:
#Your code for Exercise 5 goes here


<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [177]:
#Your code for part A of Exercise 6 goes here


In [178]:
#Your code for part B of Exercise 6 goes here


<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [228]:
#Your code for part A of Exercise 7 goes here


In [230]:
#Your code for part B of Exercise 7 goes here


<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [245]:
#Your code for part A of Exercise 8 goes here


In [255]:
#Your code for part B of Exercise 8 goes here


<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [364]:
#Your code for part A of Exercise 9 goes here


In [ ]:
#Your code for part B of Exercise 9 goes here


In [367]:
#Your code for part C of Exercise 9 goes here


In [368]:
#Your code for part D of Exercise 9 goes here


<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [383]:
#Your code for part A of Exercise 10 goes here


In [391]:
#Your code for part A of Exercise 10 goes here
